Repository MicrosoftDocs/windows-uwp.ja-jp, pull requests merged in 2019-07, with the labels that each got.

#7 [LOC] Back-Translation "Windows こんにちは"→"Windows Hello"
  windows-apps-src/security/companion-device-unlock.md
Labels: Accepted

#2 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  windows-apps-src/enterprise/index.md
Labels: Accepted, Linguistic Suggestion

#1 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md
Labels: Accepted, Linguistic Suggestion

#3 [LOC] Back-Translation "XAML 諸島"→"XAML Islands"
  hub/apps/desktop/modernize/using-the-xaml-hosting-api.md
Labels: Accepted, Linguistic Suggestion

#5 [LOC] Back-Translation "XAML 諸島"→"XAML Islands"
  hub/apps/desktop/modernize/xaml-islands.md
Labels: Accepted, Linguistic Suggestion

#6 [LOC] Back-Translation "Windows こんにちは"→"Windows Hello"
  windows-apps-src/security/microsoft-passport-login.md
Labels: Accepted, Linguistic Suggestion

#16 [LOC] Back-Translation
  windows-apps-src/launch-resume/reserved-uri-scheme-names.md
Labels: Accepted

#17 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  windows-apps-src/xaml-platform/index.md
Labels: Accepted, Linguistic Suggestion

#22 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  windows-apps-src/updates-and-versions/choose-a-uwp-version.md
Labels: Accepted

#21 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  windows-apps-src/whats-new/windows-10-build-18362.md
Labels: Accepted

#20 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  windows-apps-src/whats-new/windows-10-build-17763.md
Labels: Accepted

#23 [LOC] Back-Translation "XAML 諸島"→"XAML Islands"
  hub/apps/desktop/modernize/modernize-wpf-tutorial-2.md
Labels: Accepted

#24 [LOC] Back-Translation "XAML 島々"→"XAML Islands"
  hub/apps/desktop/modernize/xaml-islands.md
Labels: Accepted

#27 [LOC] Back-Translation "XAML の島"→"XAML Islands"
  hub/apps/desktop/modernize/using-the-xaml-hosting-api.md
Labels: Accepted

#26 [LOC] Back-Translation "XAML の島"→"XAML Islands"
  hub/apps/desktop/modernize/desktop-to-uwp-extend.md
Labels: Accepted

#30 [LOC] Back-Translation "ビジュアル層"→"ビジュアル レイヤー"
  hub/apps/desktop/modernize/using-the-visual-layer-with-windows-forms.md
Labels: Accepted

#29 [LOC] Back-Translation "ビジュアル層"→"ビジュアル レイヤー"
  hub/apps/desktop/modernize/using-the-visual-layer-with-win32.md
Labels: Accepted

#28 [LOC] Back-Translation "ビジュアル層"→"ビジュアル レイヤー"
  hub/apps/desktop/modernize/using-the-visual-layer-with-wpf.md
Labels: Accepted

#32 [LOC] Back-Translation "カテゴリ"→"Category"
  hub/apps/desktop/modernize/desktop-to-uwp-extensions.md
Labels: Accepted, Source Issue

#42 [LOC] Back-Translation "Windows こんにちは"→"Windows Hello"
  windows-apps-src/security/microsoft-passport.md
Labels: Accepted

#43 [LOC] Back-Translation "Windows こんにちは"→"Windows Hello"
  windows-apps-src/security/microsoft-passport-login-auth-service.md
Labels: Accepted

#34 Typo "XAML Islands"→"XAML Island"
  hub/apps/desktop/modernize/desktop-to-uwp-extend.md
Labels: Accepted, Linguistic Suggestion

#39 [LOC] Back-Translation "XAML 諸島"→"XAML Islands"
  hub/apps/desktop/modernize/modernize-wpf-tutorial.md
Labels: Accepted, Linguistic Suggestion

#38 [LOC] Back-Translation "XAML の島"→"XAML Islands"
  hub/apps/desktop/modernize/modernize-wpf-tutorial-1.md
Labels: Accepted, Linguistic Suggestion

#37 [LOC] Back-Translation "XAML 諸島"→"XAML Islands"
  hub/apps/desktop/modernize/modernize-wpf-tutorial-3.md
Labels: Accepted, Linguistic Suggestion

#35 Update toc.yml "XAML アイランド"→"XAML Islands"
  hub/toc.yml
Labels: Accepted, Linguistic Suggestion

#40 fix "作成「こんにちは, world」アプリ (XAML)"→""Hello, world" アプリを作成する (XAML)"
  windows-apps-src/design/input/radialcontroller-walkthrough.md
Labels: Accepted, Linguistic Suggestion

#41 fix "C + を使用して"→"C++/WinRTを使用して"
  windows-apps-src/winrt-components/walkthrough-creating-a-basic-windows-runtime-component-in-cpp-and-calling-it-from-javascript-or-csharp.md
Labels: Accepted, Linguistic Suggestion

#54 fix "「こんにちは, world!」"→""Hello, world!""
  windows-apps-src/composition/composition-native-interop.md
Labels: Accepted

#45 [LOC] Back-Translation "XAML 島"→"XAML Island"
  hub/apps/desktop/modernize/xaml-islands.md
Labels: Accepted, Linguistic Suggestion

#46 [LOC] Back-Translation "ビジュアル層"→"ビジュアル レイヤー"
  windows-apps-src/composition/visual-layer.md
Labels: Accepted, Linguistic Suggestion

#49 [LOC] Back-Translation "ビジュアル層"→"ビジュアル レイヤー"
  windows-apps-src/composition/composition-tailoring.md
Labels: Accepted, Linguistic Suggestion

#47 [LOC] Back-Translation "ビジュアル層"→"ビジュアル レイヤー"
  windows-apps-src/design/motion/xaml-property-animations.md
Labels: Accepted, Linguistic Suggestion

#48 [LOC] Back-Translation "ビジュアル層"→"ビジュアル レイヤー"
  windows-apps-src/composition/composition-shadows.md
Labels: Linguistic Suggestion, Partially Accepted

#50 [LOC] Back-Translation " Windows インク"→"Windows Ink"
  hub/apps/features-and-technologies.md
Labels: Accepted, Linguistic Suggestion

#52 [LOC] Back-Translation "Windows インク"→"Windows Ink"
  windows-apps-src/design/input/pen-and-stylus-interactions.md
Labels: Accepted, Linguistic Suggestion

#53 fix "「こんにちは, world!」"→""Hello, world!""
  windows-apps-src/app-resources/using-mrt-for-converted-desktop-apps-and-games.md
Labels: Accepted, Linguistic Suggestion

#55 fix "Windows インク ツールバー"→"Windows Ink ツール バー"
  windows-apps-src/design/input/ink-toolbar.md
Labels: Accepted, Linguistic Suggestion

#56 fix "「こんにちは, world!」"→""Hello, world!""
  windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md
Labels: Accepted, Linguistic Suggestion

#57 [LOC] Back-Translation "XAML 島"→"XAML Islands"
  hub/apps/desktop/modernize/xaml-islands.md
Labels: Accepted, Linguistic Suggestion

#58 [LOC] Back-Translation "XAML 島"→"XAML Island”
  hub/apps/desktop/modernize/using-the-xaml-hosting-api.md
Labels: Accepted, Linguistic Suggestion

#59 fix "「こんにちは, world!」"→""Hello, world!""
  windows-apps-src/composition/composition-native-interop.md
Labels: Accepted, Linguistic Suggestion

#67 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  hub/apps/desktop/modernize/index.md
Labels: Accepted

#66 [LOC] Back-Translation "XAML アイランド"→"XAML Islands"
  windows-apps-src/whats-new/windows-10-build-17763.md
Labels: Accepted

#62 「UWP アプリ設計の概要」の「4 の倍数」を日本語に翻訳
  windows-apps-src/design/basics/design-and-ui-intro.md
Labels: Accepted, Source Issue

#68 fix "C +/cli WinRT"→"C++/WinRT"
  windows-apps-src/xaml-platform/custom-attached-properties.md
Labels: Accepted, Linguistic Suggestion

#61 Back-Translation "カーソル & ポインターのサイズ"→"カーソルとポインターのサイズ"
  windows-apps-src/launch-resume/launch-settings-app.md
Labels: Accepted, Linguistic Suggestion

#65 [LOC] Back-Translation "XAML 諸島"→"XAML Islands"
  hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md
Labels: Accepted, Linguistic Suggestion

#69 [EN->JA][UWP アプリ設計の概要]の[シェル]セクションを翻訳
  windows-apps-src/design/basics/design-and-ui-intro.md
Labels: Accepted

#70 [EN->JA][UWP アプリ設計の概要]の[入力]セクションを翻訳
  windows-apps-src/design/basics/design-and-ui-intro.md
Labels: Accepted

#18 Broken link "[XAML Islands]"
  windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md
Labels: In Progress, Source Issue
